[build]
  command = "npm install --force && npx prisma generate && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[functions]]
  name = "login"
  path = "netlify/functions/login.ts"

[[functions]]
  name = "register"
  path = "netlify/functions/register.ts"

[[functions]]
  name = "profile"
  path = "netlify/functions/profile.ts"