[build]
  command = "npm install --force && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = "dist"

# Optimize function bundling for Netlify
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
